### ISSUE TITLE
Error while pulling submodules

### ISSUE THREAD

**Issue by BJNFNE** [bismurphy/Aironauts-decomp#1]
Hi, i get this error after cloning the repository and running git submodule update --init --recursive, after confirming the fingerprint with yes i got this error and it fails: This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Konnte nicht vom Remote-Repository lesen.

Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
und das Repository existiert.
fatal: klonen von »git@github.com:simonlindholm/asm-differ.git« in Submodul-Pfad »/home/bjnfne/Aironauts-decomp/tools/asm-differ« fehlgeschlagen
Fehler beim Klonen von 'tools/asm-differ'. Weiterer Versuch geplant
Klone nach '/home/bjnfne/Aironauts-decomp/tools/asm-differ' …
git@github.com: Permission denied (publickey).
fatal: Konnte nicht vom Remote-Repository lesen.

Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
und das Repository existiert.
fatal: klonen von »git@github.com:simonlindholm/asm-differ.git« in Submodul-Pfad »/home/bjnfne/Aironauts-decomp/tools/asm-differ« fehlgeschlagen
Zweiter Versuch 'tools/asm-differ' zu klonen fehlgeschlagen, breche ab.

**Comment by bismurphy** [comment]
This seems like an issue with your Github SSH key setup, not an issue with this repository. Regardless, the only current module is asm-differ, which is not critical for building the game, so you can safely skip the submodule step.

**Comment by BJNFNE** [comment]
Thank you :)
